#!/bin/sh

# Desktop background
feh --bg-max ~/wallpapers/symlink 
xset dpms 7200 7200 7200
insync start &
dropbox &

udiskie -2t &
nm-applet &
parcellite &

firefox &
psi &
thunderbird &
gtk-redshift -l 50:15 &
